name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: deploy to EC2
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'
      - run: npm ci
        
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: server/
          remote_host: ec2-18-223-39-160.us-east-2.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
    
   
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ec2-18-223-39-160.us-east-2.compute.amazonaws.com
            USER_NAME: ubuntu
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v18.16.0/bin
              # Now we have got the access of EC2 and we will start the deploy.
              
              cd server &&
              touch .env &&
              echo "${{ secrets.PROD_ENV_FILE }}" > .env &&
              pm2 restart server.js --update-env
              '
